### ISSUE TITLE
Initial comments on the paper

### ISSUE THREAD

**Issue by colm-connaughton** [ACabrejas/IEEE_ITSC2020_WARP#1]
Hi Alvaro - here are some comments on the paper. I think it is easier to put them here rather than firing emails back at forth.

* Firstly, your writing style has really improved a lot. Whatever is in the water in the Turing is clearly very good for you :-)
* Although I like that you have managed to find a way to get a WARWICK acronym(!!!), I wonder whether this might be asking for trouble further down the road. Something like Wavelet Augmented Regression Profiling would give you a cool acronym without potentially aggravating people.
* Speaking of acronyms, be careful with yours in the paper: NTIS = National Traffic Information Service (not National Traffic Information System), MAPE = Mean Absolute Percentage Error (not Mean Average Percentage Error).
* In the introduction, you claim that this work removes the heuristic threshold set in the previous paper but Table I still has heuristic thresholds.
* Section II starts with an incorrect description of the data. Link level travel times are not measured directly by the MIDAS loops. Rather the travel times are derived quantities that are published (with some delay) by INRIX. They are probably obtained from a synthesis of several different data sources.
* You have done a good job of spelling out the requirements for the new algorithm but I think it will be very difficult for a reviewer to follow the description of the algorithm on page 4.  
* You have not said much about the wavelets part of the algorithm - probably not enough to allow non-specialists to understand. Probably you need to talk a bit more about Fig 4 and what it means. 
* Although I'm pointing out lots of snags here, overall I think this is really good. Your introduction and motivation and description of the algorithmic requirements make a much more convincing case than we had previously.

**Comment by ACabrejas** [comment]
Just a head's up, I am back on this.
I am giving the whole thing some love. Hope to finish at the end of the day.

I have partially re-written the first 5 sections of the document and processed all of your comments above.
My ETA for the whole document being ready is today evening.

Please give it a check at your earliest convenience, but don't worry if you take a month to see this comment, I will write you an email whenever is ready.

There are 2 weeks until the deadline.

**Comment by ACabrejas** [comment]
FYI: Section 5C is completely new.
