### ISSUE TITLE
Style Improvements

### ISSUE THREAD

**Issue by ChihiroBanana** [ACabrejas/IEEE_ITSC2020_WARP#2]
I.A.Paragraph 2, Sentence 2: Subject-Verb agreement (This display-->This displays)
I.A.Paragraph 3, Sentence 1: Consider re-phrasing  (governmental agencies publicly available data-->publicly available data from governmental agencies) (Otherwise, apostrophe after s in agencies)
I.A.Paragraph 3, Sentence 2: Singular to plural (Spectral and statistical analysis-->analyses) 
I.B.Paragraph 1, Sentence 3: I wasn't sure of what you meant by "having a high relevance"; high relevance to x? Or do you mean there's been a lot of focus on it?
I.B.Paragraph 1, Sentence 4: Consider changing don't-->do not
I.B.Paragraph 1, last sentence: No comma needed after "The work presented here"

**Comment by ChihiroBanana** [comment]
II.Paragraph 1, Sentence 2: No comma needed after "section of road"
II.Paragraph 1, Sentence 4: Apostrophe needed after drivers in "collective drivers beahviour"
II.Paragraph 1, Sentence 5: Pronoun-noun agreement (this collective dynamics-->these collective dynamics)
II.Paragraph 1, Sentence 5: I'm not sure what you mean after the semi-colon--is that the effect of the collective dynamics that you refer to in the sentence before the semi-colon? (Also, a semi-colon needs to be followed by a full sentence unless it is in a list :))
II.Paragraph 1, Sentence 8: Is there an extra word here? "several times fold the normal amount"
II.Paragraph 1, Sentence 10: Capitalise "figure 2"

**Comment by ChihiroBanana** [comment]
III.A.Paragraph 1, last sentence: Change "if an large deviation"-->"if a large deviation"
III.B.Paragraph 1, Sentence 2: Change "following"-->falling
III.B.Paragraph 1, Sentence 3: Change "joint"-->joined
III.B.Paragraph 1, Sentence 6: Subject-Verb agreement: "These requirements often leads to"-->"These requirements often lead to"
III.B.Paragraph 1, Sentence 6: Change "additional efforts for continually train"-->"additional efforts for continually training" or "additional efforts to continually train"

**Comment by ChihiroBanana** [comment]
IV, Sentence 1: Past tense to present tense?

**Comment by ChihiroBanana** [comment]
V.A.Paragraph 2, Sentence 2: Comma needed after "recurring congestion"
V.A.Paragraph 2, last sentence: No comma needed after "step of the decomposition"
V.B.Paragraph 1, Sentence 4: No comma needed after "(x axis)"
V.B.Paragraph 1, Sentence 4: Comma needed after "namely"
V.B.Paragraph 3, last sentence: Change "an non-tuned version" to "a non-tuned version"
V.C.Paragraph 2, Sentence 1: Change "the other will only" to "the other, which will only"

**Comment by ChihiroBanana** [comment]
VI.C.Paragraph 1, Sentence 1: I'm not sure what might be correct, did you mean "STL is resilient to outliers and [I've swapped the comma here for an and] can manage any combination of seasonalities, allowing to control their change..."?
VI.C.Paragraph 2, Sentence 2: Consider dividing into two sentences with a period after Sw.

**Comment by ChihiroBanana** [comment]
VII. Paragraph 2, Sentence 1: Change comma to semi-colon after "evening rush hours"
VII. Paragraph 3, Sentence 1: Typo "thhat"

**Comment by ChihiroBanana** [comment]
VIII. Sentence 1: I wasn't sure what you meant with "keeping one parameter"? 
VIII. Sentence 3: Change "can" to "could" for consistency

**Comment by ACabrejas** [comment]
changes included. issue closed.
